# /etc/dnsmasq.conf

server=1.1.1.1
server=8.8.8.8
cache-size=1500
# listen-address must have 127.0.0.1 and one lan ip of this dns server, in this case is set to 192.168.1.220
listen-address=127.0.0.1,192.168.1.220
domain-needed
bogus-priv
expand-hosts
no-resolv
domain=lan
local=/lan/
