#!/bin/bash
# This script sets up git with GPG signing and pass for credential management.

sudo apt update && sudo apt install -y git gpg pass dotnet-sdk-8.0
dotnet tool install -g git-credential-manager
echo "export PATH=\"$PATH:$HOME/.dotnet/tools\"" >> ~/.bashrc
source ~/.bashrc

git-credential-manager configure
git config --global user.name "Duc"
git config --global user.email "48994241+nduc03@users.noreply.github.com"
git config --global credential.credentialStore gpg
gpg --gen-key

read -p "Enter the ID generated by gpg: " ID
pass init "$ID"